services:
  airflow:
    build:
      dockerfile: airflow.Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-1000}:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./source:/opt/airflow/source
    networks:
            - airflow-net
    environment:
        - PYTHONPATH=/opt/airflow

networks:
  airflow-net:
    driver: bridge

volumes:
  spark-data: