services:
  airflow:
    build:
      dockerfile: airflow.Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-1000}:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./source:/opt/airflow/source
    networks:
            - airflow-net
    environment:
        - PYTHONPATH=/opt/airflow
#  spark-master:
#      image: bitnamilegacy/spark:3.5
#      environment:
#        - SPARK_MODE=master
#        - SPARK_RPC_AUTHENTICATION_ENABLED=no
#        - SPARK_RPC_ENCRYPTION_ENABLED=no
#        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#        - SPARK_SSL_ENABLED=no
#        - SPARK_MASTER_WEBUI_PORT=8081
#      ports:
#        - "8081:8081"
#        - "7077:7077"
#      volumes:
#        - spark-data:/bitnami
#        - ./source:/source
#        - ./apps:/opt/spark-apps
#        - ./data:/opt/spark-data
#      networks:
#        - airflow-net
    
#  spark-worker:
#    image: bitnamilegacy/spark:3.5
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=2G
#      - SPARK_WORKER_CORES=2
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    volumes:
#      - spark-data:/bitnami
#      - ./source:/source
#      - ./apps:/opt/spark-apps
#      - ./data:/opt/spark-data
#    depends_on:
#      - spark-master
#    networks:
#      - airflow-net


networks:
  airflow-net:
    driver: bridge

volumes:
  spark-data: