services:

  airflow:
    build:
      dockerfile: airflow.Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

#  app:
#    build: 
#      dockerfile: app.Dockerfile
    